VERSION: 1
APPNAME: 'Hummingbot Gateway API'

PORT: 5000

IP_WHITELIST: []
HUMMINGBOT_INSTANCE_ID: '67618e88c8b8f52342e61c6e46dc2571fa48543b'
LOG_PATH: './logs'
LOG_TO_STDOUT: true
GMT_OFFSET: +0800

# certs
CERT_PATH: ''
CERT_PASSPHRASE: ''

# chain environments
ETHEREUM_CHAIN: mainnet
AVALANCHE_CHAIN: avalanche
SOLANA_CHAIN: mainnet-beta

# Infura
INFURA_KEY: ''

# Eth Gas Station
ETH_GAS_STATION_ENABLE: true
ETH_GAS_STATION_API_KEY: ''
ETH_GAS_STATION_GAS_LEVEL: fast
ETH_GAS_STATION_REFRESH_TIME: 60
ETH_MANUAL_GAS_PRICE: 100

# Avax Gas Station
AVAX_MANUAL_GAS_PRICE: 225

# Uniswap
UNISWAP_ALLOWED_SLIPPAGE: '1/100'
UNISWAP_GAS_LIMIT: 150688
UNISWAP_TTL: 300

# Pangolin
PANGOLIN_ALLOWED_SLIPPAGE: '1/100'
PANGOLIN_GAS_LIMIT: 23012
PANGOLIN_TTL: 300

# Solana
SOLANA_CUSTOM_RPC:
SOLANA_TRANSACTION_LAMPORTS: 5000
SOLANA_LAMPORTS_TO_SOL: 0.000000001
SOLANA_TTL: 75  # After 150 slots (0.5s per slot) a transaction is dropped, if not processed
SOLANA_TOKEN_PROGRAM: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA

# Mango
MANGO_GROUP: mainnet.1

# Telemetry
ENABLE_TELEMETRY: false
