repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      types: ['file']
      files: \.(py|pyx|pxd)$
    - id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
    -   id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
