repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      types: ['file']
      files: \.(py|pyx|pxd)$
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      files: "\\.(py)$"
      args: [--settings-path=pyproject.toml]
