paths:
  /avalanche/pangolin:
    get:
      tags:
        - 'pangolin'
      summary: 'View the Pangoling router that gateway is configured to use'
      description: 'The user can change this by editing src/chains/avalanche/config/ethereum.config.ts'
      operationId: 'root'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Pangolin config'
          schema:
            $ref: '#/definitions/UniswapConfigResponse'

  /avalanche/pangolin/price:
    post:
      tags:
        - 'pangolin'
      summary: 'Get the Pangolin price for a quote base pair'
      operationId: 'poll'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/UniswapPriceRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/UniswapPriceResponse'

  /avalanche/pangolin/trade:
    post:
      tags:
        - 'pangolin'
      summary: 'Perform a Pangolin trade'
      operationId: 'trade'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/UniswapTradeRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/UniswapTradeResponse'
