paths:
  /eth:
    get:
      tags:
        - 'eth'
      summary: 'View the Ethereum network and RPC URL that gateway is configured to use'
      description: 'The user can change this by editing src/chains/ethereum/ethereum.config.ts'
      operationId: 'root'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Ethereum config'
          schema:
            $ref: '#/definitions/EthereumConfigResponse'

  /eth/nonce:
    post:
      tags:
        - 'eth'
      summary: 'Get the nonce for the provided Ethereum private key'
      operationId: 'nonce'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumNonceRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumNonceResponse'

  /eth/allowances:
    post:
      tags:
        - 'eth'
      summary: 'Get the ERC20 allowances for a spender on a given private key'
      operationId: 'allowances'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumAllowancesRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumAllowancesResponse'

  /eth/balances:
    post:
      tags:
        - 'eth'
      summary: 'Get the balances of an Ethereum private key'
      operationId: 'balances'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumBalancesRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumBalancesResponse'

  /eth/approve:
    post:
      tags:
        - 'eth'
      summary: 'Create an ERC20 approval for a spender on an Ethereum private key'
      operationId: 'approve'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumApproveRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumApproveResponse'

  /eth/poll:
    post:
      tags:
        - 'eth'
      summary: 'Poll the status of an Ethereum transaction'
      operationId: 'poll'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumPollRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumPollResponse'
  
  /eth/cancel:
    post:
      tags:
        - 'eth'
      summary: 'Cancel Ethereum transaction'
      operationId: 'cancel'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumCancelRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumCancelResponse'
  
