paths:
  /eth/uniswap:
    get:
      tags:
        - 'uniswap'
      summary: 'View the Uniswap Router that gateway is configured to use'
      description: 'The user can change this by editing src/chains/ethereum/uniswap/uniswap.config.ts'
      operationId: 'root'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Uniswap config'
          schema:
            $ref: '#/definitions/UniswapConfigResponse'

  /eth/uniswap/price:
    post:
      tags:
        - 'uniswap'
      summary: 'Get the Uniswap V2 price for a quote base pair'
      operationId: 'poll'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/UniswapPriceRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/UniswapPriceResponse'

  /eth/uniswap/trade:
    post:
      tags:
        - 'uniswap'
      summary: 'Perform a Uniswap V2 trade'
      operationId: 'trade'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/UniswapTradeRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/UniswapTradeResponse'
  
