paths:
  /:
    get:
      summary: 'Ping the server to see that it is running'
      produces:
        - 'application/json'
      responses:
        '200'
  /config:
    get:
      summary: 'Get every gateway configuration option'
      produces:
        - 'application/json'
      responses:
        '200'
  /config/update:
    post:
      summary: 'Updates Gateway configuration'
      operationId: 'update'
      consumes:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/ConfigUpdateRequest'
      responses:
        '200'
  /status:
    get:
      summary: 'Returns a list of the currently connected networks'
      produces:
        - 'application/json'
      responses:
        '200'
