paths:
  /:
    get:
      summary: 'Ping the server to see that it is running'
      produces:
        - 'application/json'
      responses:
        '200'
  /config:
    get:
      summary: 'Get gateway configuration'
      produces:
        - 'application/json'
      responses:
        '200'
  /config/update:
    post:
      summary: 'Ping the server to see that it is running'
      produces:
        - 'application/json'
      responses:
        '200'
