# Project info
site_name: hummingbot docs
site_description: 'Docs for hummingbot, the open source crypto market making bot'
site_author: 'CoinAlpha, Inc.'
site_url: 'https://docs.hummingbot.io'

# Repository
repo_name: 'coinalpha/hummingbot'
repo_url: 'https://github.com/coinalpha/hummingbot'
edit_uri: 'blob/master/documentation/docs/'

# Copyright
copyright: 'Copyright &copy; 2019 CoinAlpha, Inc.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
      text: 'Roboto'
      code: 'Roboto Mono'
  feature:
    tabs: true

# Customization
extra:
  search:
    language: 'en'
  social:
    - type: 'globe'
      link: 'https://www.hummingbot.io'
    - type: 'github'
      link: 'https://github.com/coinalpha/hummingbot'
    - type: 'twitter'
      link: 'https://twitter.com/hummingbot_io'
google_analytics:
  - 'UA-119262087-3'
  - 'auto'
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/heap.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
    - General:
      - Getting Started: index.md
      - Learn about Hummingbot:
        - FAQ: faq.md
        - Whitepaper: whitepaper.md
        - Timeline: roadmap.md
        - Useful Terminology: glossary.md
      - Quickstart:
        - 0. Setup: quickstart/index.md
        - 1. Install Hummingbot: quickstart/1-install.md
        - 2. Configure a Bot: quickstart/2-configure-bot.md
        - 3. Run a Bot: quickstart/3-run-bot.md
      - Cheatsheets:
        - Cheatsheets Overview: cheatsheets/index.md
        - Docker Commands: cheatsheets/docker.md
        - Source Commands: cheatsheets/source.md
        - Client Commands: cheatsheets/client.md
      - Bounties:
        - FAQ: bounties/faq.md
        - Active Bounties:
          - Harmony $ONE Makers: bounties/active/harmony.md
      - Get Help:
        - Contact and Support: support/index.md
        - Troubleshooting: support/troubleshooting.md
        - Bug Bounty Program: support/bug-bounty-program.md
        - 中文 Github repo: https://github.com/coinalpha/hummingbot_chinese
    - User Manual:
      - Intro: manual.md
      - Installation:
        - Installation Overview: installation/index.md
        - Setup a Cloud Server: installation/cloud.md
        - Install on Linux: installation/linux.md
        - Install on MacOS: installation/macOS.md
        - Install on Windows: installation/windows.md
        - Install from Source:
          - Linux: installation/from-source/linux.md
          - macOS: installation/from-source/macOS.md
          - Windows: installation/from-source/windows.md
      - Configuration:
        - Configuring Hummingbot: operation/configuration.md
        - API Keys: installation/api-keys.md
        - Ethereum Wallet: installation/wallet.md
        - Ethereum Node: installation/node/node.md
        - Get a Free Ethereum Node: installation/node/infura.md
      - Operation:
        - Using the Client: operation/client.md
        - Running Trading Bots: operation/running-bots.md
        - Tips for Cloud Users: operation/running-bots-in-the-cloud.md
      - Connectors:
        - Connectors Overview: connectors/index.md
        - Binance: connectors/binance.md
        - Coinbase Pro: connectors/coinbase.md
        - DDEX: connectors/ddex.md
        - IDEX: connectors/idex.md
        - Radar Relay: connectors/radar-relay.md
        - 0x Relayers: connectors/0x.md
      - Strategies:
        - Strategies Overview: strategies/index.md
        - Cross-exchange market making: strategies/cross-exchange-market-making.md
        - Arbitrage: strategies/arbitrage.md
        - Cross-Exchange Market Making: strategies/cross-exchange-market-making.md
        - Pure Market Making: strategies/pure-market-making.md
        - Discovery: strategies/discovery.md
      - Data Feeds:
        - Data Feeds Overview: feeds.md
      - Utilities:
        - Logs and Logging: operation/logging.md
        - Using Exchange Rates: operation/exchange-rates.md
        - Integrating Telegram: operation/telegram.md
        - Debug Console: operation/debug.md
    - Release Notes:
      - About Releases: release-notes/index.md
      - 0.10.1: release-notes/0.10.1.md
      - 0.10.0: release-notes/0.10.0.md
      - 0.9.1: release-notes/0.9.1.md
      - 0.9.0: release-notes/0.9.0.md
      - 0.8.1: release-notes/0.8.1.md
      - 0.8.0: release-notes/0.8.0.md
      - 0.7.0: release-notes/0.7.0.md
      - 0.6.0: release-notes/0.6.0.md
      - 0.5.1: release-notes/0.5.1.md
      - 0.5.0: release-notes/0.5.0.md
      - 0.4.0: release-notes/0.4.0.md
      - 0.3.1 (beta): release-notes/0.3.1.md
      - 0.3.0: release-notes/0.3.0.md
      - 0.2.0: release-notes/0.2.0.md
