# Project info
site_name: hummingbot docs
site_description: 'Docs for hummingbot, the open source crypto market making bot'
site_author: 'CoinAlpha, Inc.'
site_url: 'https://docs.hummingbot.io'

# Repository
repo_name: 'coinalpha/hummingbot'
repo_url: 'https://github.com/coinalpha/hummingbot'
edit_uri: 'blob/master/documentation/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 CoinAlpha, Inc.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
      text: 'Roboto'
      code: 'Roboto Mono'
  feature:
    tabs: true

# Customization
extra:
  search:
    language: 'en'
  social:
    - type: 'globe'
      link: 'https://www.hummingbot.io'
    - type: 'github'
      link: 'https://github.com/coinalpha/hummingbot'
    - type: 'twitter'
      link: 'https://twitter.com/hummingbot_io'
google_analytics:
  - 'UA-119262087-3'
  - 'auto'
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/heap.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - General:
    - Overview: index.md
    - Liquidity Mining: liquidity-mining.md
    - FAQs:
      - Overview: faq/index.md
      - Hummingbot FAQs: faq/hummingbot.md
      - Market Making FAQs: faq/market-making.md
      - Liquidity Mining FAQs: faq/liquidity-mining.md
      - Troubleshooting FAQs: faq/troubleshooting.md
    - Quickstart:
      - Install: quickstart/index.md
      - Install-temp: quickstart/2-install.md
      - Configure: quickstart/3-configure-bot.md
      - Run: quickstart/4-run-bot.md
      - LM-Sign up: quickstart/1-sign-up.md
      - LM-Connect exchanges: quickstart/2-connect-exchanges.md
      - LM-Run Hummingbot: quickstart/3-run-bot.md
      - LM-Track earnings: quickstart/4-track-earnings.md
    - Support:
      - Overview: support/index.md
      - Commands: support/commands.md
    - Installation:
      - Overview: installation/index.md
      - Setup a Cloud Server: installation/cloud.md
      - Install via Binary:
        - Windows: installation/from-binary/windows.md
        - macOS: installation/from-binary/macos.md
      - Install via Docker:
        - Linux: installation/via-docker/linux.md
        - macOS: installation/via-docker/macOS.md
        - Windows: installation/via-docker/windows.md
      - Install from Source:
        - Linux: installation/from-source/linux.md
        - macOS: installation/from-source/macOS.md
        - Windows: installation/from-source/windows.md
      - Updating Hummingbot: installation/updating.md
    - Operation:
      - Overview: operation/index.md
      - Configuring Hummingbot: operation/configuration.md
      - Performance Analysis: operation/performance-analysis.md
      - Paper Trading Mode: operation/paper-trade.md
      - Running Trading Bots: operation/running-bots.md
    - Strategies:
      - Overview: strategies/index.md
      - Pure Market Making: strategies/pure-market-making.md
      - Cross-Exchange Market Making: strategies/cross-exchange-market-making.md
      - Arbitrage: strategies/arbitrage.md
      - Discovery: strategies/discovery.md
    - Connectors:
      - Overview: connectors/index.md
      - Binance: connectors/binance.md
      - Coinbase Pro: connectors/coinbase.md
      - Huobi Global: connectors/huobi.md
      - Bittrex Global: connectors/bittrex.md
      - Liquid: connectors/liquid.md
      - KuCoin: connectors/kucoin.md
      - Radar Relay: connectors/radar-relay.md
      - Community Connectors:
        - Bamboo Relay: connectors/bamboo-relay.md
        - Dolomite: connectors/dolomite.md
    - Advanced:
      - Running Multiple Bots: advanced/running-multiple-bots.md
      - Trading Strategy Autostart: advanced/autostart.md
      - Kill Switch: advanced/kill-switch.md
      - Logs and Logging: advanced/logging.md
      - Using Exchange Rates: advanced/exchange-rates.md
      - Integrating Telegram: advanced/telegram.md
      - Ethereum Wallet: advanced/wallet.md
      - Ethereum Node: advanced/node/index.md
      - Get a Free Ethereum Node: advanced/node/infura.md
  - Developer Manual:
      - Intro: developers/index.md
      - Getting Started:
        - Intro: developers/gettingstarted/index.md
        - Linux:
          - Intro: developers/gettingstarted/linux/index.md
          - 1. Installing Hummingbot: developers/gettingstarted/linux/1-installing.md
          - 2. Using Hummingbot: developers/gettingstarted/linux/2-using.md
          - 3. Re-compiling Hummingbot: developers/gettingstarted/linux/3-recompiling.md
        - macOS:
          - Intro: developers/gettingstarted/mac/index.md
          - 1. Installing Prerequisites: developers/gettingstarted/mac/1-prereqs.md
          - 2. Installing Hummingbot: developers/gettingstarted/mac/2-installing.md
          - 3. Using Hummingbot: developers/gettingstarted/mac/3-using.md
          - 4. Re-compiling Hummingbot: developers/gettingstarted/mac/4-recompiling.md
        - Windows:
          - Intro: developers/gettingstarted/windows/index.md
          - 1. Installing Hummingbot: developers/gettingstarted/windows/1-installing.md
          - 2. Using Hummingbot: developers/gettingstarted/windows/2-using.md
          - 3. Re-compiling Hummingbot: developers/gettingstarted/windows/3-recompiling.md
      - Strategies:
        - Architecture: developers/strategies/index.md
        - Arbitrage: developers/strategies/arbitrage.md
        - Cross-Exchange Market Making: developers/strategies/cross-exchange-market-making.md
        - Pure Market Making: developers/strategies/pure-market-making.md
        - Discovery: developers/strategies/discovery.md
        - TWAP: developers/strategies/twap.md
      - Connectors:
        - Intro: developers/connectors/index.md
        - Architecture: developers/connectors/architecture.md
        - Order Lifecycle: developers/connectors/order-lifecycle.md
        - Building Connectors: developers/connectors/tutorial.md
        - Miscellaneous: developers/connectors/miscellaneous.md
      - Tutorial (WIP):
        - Intro: developers/tutorial/index.md
        - Perform Trade: developers/tutorial/perform-trade.md
        - Simple Trade: developers/tutorial/simple-trade.md
      - Debug Console: developers/debug.md
      - Configuration: developers/config.md
  - Release Notes:
    - About Releases: release-notes/index.md
    - 0.24.0: release-notes/0.24.0.md
    - 0.23.0: release-notes/0.23.0.md
    - 0.22.0: release-notes/0.22.0.md
    - 0.21.0: release-notes/0.21.0.md
    - 0.20.0: release-notes/0.20.0.md
    - 0.19.1: release-notes/0.19.1.md
    - 0.19.0: release-notes/0.19.0.md
    - 0.18.1: release-notes/0.18.1.md
    - 0.18.0: release-notes/0.18.0.md
    - 0.17.1: release-notes/0.17.1.md
    - 0.17.0: release-notes/0.17.0.md
    - 0.16.0: release-notes/0.16.0.md
    - 0.15.0: release-notes/0.15.0.md
    - 0.14.0: release-notes/0.14.0.md
    - 0.13.0: release-notes/0.13.0.md
    - 0.12.1: release-notes/0.12.1.md
    - 0.12.0: release-notes/0.12.0.md
    - 0.11.1: release-notes/0.11.1.md
    - 0.11.0: release-notes/0.11.0.md
    - 0.10.1: release-notes/0.10.1.md
    - 0.10.0: release-notes/0.10.0.md
    - 0.9.1: release-notes/0.9.1.md
    - 0.9.0: release-notes/0.9.0.md
    - 0.8.1: release-notes/0.8.1.md
    - 0.8.0: release-notes/0.8.0.md
    - 0.7.0: release-notes/0.7.0.md
    - 0.6.0: release-notes/0.6.0.md
    - 0.5.1: release-notes/0.5.1.md
    - 0.5.0: release-notes/0.5.0.md
    - 0.4.0: release-notes/0.4.0.md
    - 0.3.1 (beta): release-notes/0.3.1.md
    - 0.3.0: release-notes/0.3.0.md
    - 0.2.0: release-notes/0.2.0.md
