# Project info
site_name: hummingbot docs
site_description: 'Docs for hummingbot, the open source crypto market making bot'
site_author: 'CoinAlpha, Inc.'
site_url: 'https://docs.hummingbot.io'

# Repository
repo_name: 'coinalpha/hummingbot'
repo_url: 'https://github.com/coinalpha/hummingbot'
edit_uri: 'blob/master/documentation/docs/'

# Copyright
copyright: 'Copyright &copy; 2019 CoinAlpha, Inc.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
      text: 'Roboto'
      code: 'Roboto Mono'
  feature:
    tabs: true

# Customization
extra:
  search:
    language: 'en'
  social:
    - type: 'globe'
      link: 'https://www.hummingbot.io'
    - type: 'github'
      link: 'https://github.com/coinalpha/hummingbot'
    - type: 'twitter'
      link: 'https://twitter.com/hummingbot_io'
google_analytics:
  - 'UA-119262087-3'
  - 'auto'
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/heap.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
    - General:
      - Getting Started: index.md
      - Learn about Hummingbot:
        - Hummingbot FAQs: faq.md
        - Our Whitepaper: whitepaper.md
        - Our Timeline: roadmap.md
        - Useful Terminology: glossary.md
      - Install Hummingbot:
        - Installing Overview: installation.md
        - Windows: installation/docker_windows.md
        - MacOS: installation/docker_macOS.md
        - Linux: installation/docker_linux.md
        - Cloud: installation/cloud.md
      - Run a Bot:
        - Docker Commands: installation/docker.md
        - Using API Keys: installation/api-keys.md
        - Using the Client: operation/client.md
        - Configuring Hummingbot: operation/configuration.md
        - Running Trading Bots: operation/running-bots.md
        - Tips for Cloud Users: operation/running-bots-in-the-cloud.md
      - Earn Bounties:
        - Introduction: bounties/intro.md
        - Bounty FAQ: bounties/faq.md
        - Tutorial:
          - Important Info: bounties/tutorial.md
          - 1. Install: bounties/tutorial/install.md
          - 2. Register: bounties/tutorial/register.md
          - 3. Run a bot: bounties/tutorial/bot.md
        - Active Bounties:
          - Harmony $ONE Makers: bounties/active/harmony.md
      - Get Help:
        - Contact and Support: support.md
        - Bug Bounty Program: support/bug-bounty-program.md
    - User Guide:
      - Overview: guide.md
      - Installation from Source:
        - Windows: installation/windows.md
        - macOS: installation/macOS.md
        - Linux/Cloud: installation/linux.md
      - Wallets and Nodes:
        - Ethereum Wallet: installation/wallet.md
        - Ethereum Node:
          - Using Ethereum Nodes: installation/node/node.md
          - Set Up a Free Node: installation/node/infura.md
      - Connectors:
        - About Connectors: connectors.md
        - Binance: connectors/binance.md
        - Coinbase Pro: connectors/coinbase.md
        - DDEX: connectors/ddex.md
        - IDEX: connectors/idex.md
        - Radar Relay: connectors/radar-relay.md
        - 0x Relayers: connectors/0x.md
      - Strategies:
        - Strategy Overview: strategies.md
        - Cross-exchange market making: strategies/cross-exchange-market-making.md
        - Arbitrage: strategies/arbitrage.md
        - Cross-Exchange Market Making: strategies/cross-exchange-market-making.md
        - Pure Market Making: strategies/pure-market-making.md
        - Discovery: strategies/discovery.md
      - Data Feeds:
        - Overview: feeds.md
      - Utilities:
        - Logs and Logging: operation/logging.md
        - Using Exchange Rates: operation/exchange-rates.md
        - Integrating Telegram: operation/telegram.md
      - Advanced:
        - Debug Console: operation/debug.md
    - Release Notes:
      - About Releases: release-notes.md
      - 0.8.1: release-notes/0.8.1.md
      - 0.8.0: release-notes/0.8.0.md
      - 0.7.0: release-notes/0.7.0.md
      - 0.6.0: release-notes/0.6.0.md
      - 0.5.1: release-notes/0.5.1.md
      - 0.5.0: release-notes/0.5.0.md
      - 0.4.0: release-notes/0.4.0.md
      - 0.3.1 (beta): release-notes/0.3.1.md
      - 0.3.0: release-notes/0.3.0.md
      - 0.2.0: release-notes/0.2.0.md
